require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe ProductsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Product. As you add validations to Product, be sure to
  # adjust the attributes here as well.
  let(:product) { FactoryBot.create(:product) }
  let(:valid_attributes) { FactoryBot.attributes_for(:product) }
  let(:invalid_attributes) { FactoryBot.attributes_for(:product, :invalid) }
  before do
    sign_in product.user
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProductsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe 'GET #index' do
    it 'returns a success response' do
      get :index, params: { user_id: product.user_id, id: product.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      get :show, params: { user_id: product.user_id, id: product.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      get :new, params: { user_id: product.user_id, id: product.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      get :edit, params: { user_id: product.user_id, id: product.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new Product' do
        expect do
          post :create, params: { user_id: product.user_id, id: product.to_param, product: valid_attributes }, session: valid_session
        end.to change(Product, :count).by(1)
      end

      it 'redirects to the created product' do
        product_id = product
        post :create, params: { user_id: product.user_id, id: product_id, product: valid_attributes }, session: valid_session
        expect(response).to redirect_to(user_product_url(id: Product.last.id))
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: { user_id: product.user_id, id: product.to_param, product: invalid_attributes }, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) { FactoryBot.attributes_for(:product, :modify) }

      it 'updates the requested product' do
        put :update, params: { user_id: product.user_id, id: product.to_param, product: new_attributes }, session: valid_session
        product.reload
        expect(product.name).to include new_attributes[:name]
      end

      it 'redirects to the product' do
        put :update, params: { user_id: product.user_id, id: product.to_param, product: valid_attributes }, session: valid_session
        expect(response).to redirect_to(user_product_url)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'edit' template)" do
        put :update, params: { user_id: product.user_id, id: product.to_param, product: invalid_attributes }, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested product' do
      expect do
        delete :destroy, params: { user_id: product.user_id, id: product.to_param }, session: valid_session
      end.to change(Product, :count).by(-1)
    end

    it 'redirects to the products list' do
      delete :destroy, params: { user_id: product.user_id, id: product.to_param }, session: valid_session
      expect(response).to redirect_to(user_products_url)
    end
  end
end
